### ISSUE TITLE
ES2015 angular issue the fetchStrategy parameter is optional of it must be an instant of enumeration

### ISSUE THREAD

**Issue by badre429** [Breeze/breeze-client#11]
after updating angular project to breeze-client@2.0.0-alpha.9 and targeting es2015 in the dev mode work fine but when we build for production we got this issue 
![issues](https://user-images.githubusercontent.com/5818051/59446055-a61f8480-8df8-11e9-9dab-795e16494de9.jpg)

**Comment by steveschmitt** [comment]
Looks like the `fetchStrategy` is getting optimized away somehow.  I'll take a look.

As a workaround, you can turn of the optimizations in your `angular.json` file:

                "production": {
                    "optimization": false,
                    "buildOptimizer": false,
                    ...
                },

**Comment by steveschmitt** [comment]
Ugh, what a pain!  The ES6 tree-shaking optimizations in Angular 8 were removing all of the internal configuration setup and adapter registration calls in Breeze.  

I was able to prevent some of the code removal with internal changes in breeze, but you will also need to change the way that you register the adapters in your code.  Please see the updated [README](https://github.com/Breeze/breeze-client/blob/master/README.md#adapter-changes) for the changes.

Fixed in breeze-client@2.0.0-alpha.12
