### ISSUE TITLE
Use IndexedDB to cache data and sync data to server in order to support PWA offline scenario

### ISSUE THREAD

**Issue by badre429** [Breeze/breeze-client#20]

**Comment by steveschmitt** [comment]
Not a bad idea.  I already know of projects that are using `entityManager.exportEntities` to save the data in local storage, but I haven't tried using IndexedDB for the purpose.

How would you propose that the data be structured?

**Comment by badre429** [comment]
IndexedDB  has query functionality breeze can used for create offline query for large data 
breeze can create IndexedDbQuery adapter that replace api query adapter in offline mode

**Comment by marcelgood** [comment]
IndexedDBs query functionality is very limited. It's mainly a key/value data store with optional additional indexes that can be used for queries. The data itself can't be queried. By default you can query by key only, and if you index additional properties of your payload you can query by them as well, but one can't query by non-indexed properties. 

We've used IndexedDBs to develop PWAs in conjunction with service workers. A PWA really needs a proper design and clear understanding of what needs to be available offline, how and when it should be refreshed updated. The various caching strategies need to be considered.

The Breeze architecture does currently not support syncing scenarios. Syncing would require a message based architecture where every small change to a property etc. is recorded as a message/event, so it can be replayed against the server when the connection comes back. PWAs can be written with Breeze, as I said we've done it, but it requires a proper understanding of what needs to be available offline and how it should be updated on the server. Any type of syncing architecture also needs a conflict resolution solution, which is really the hardest part of this. Consumer apps are relatively simple to write as PWA, because a single users generally updates their own data, but in an Enterprise app, where Breeze is mostly used, it's a whole different story if you have multiple users updating the same data while they are offline potentially. The first step is usually involves thinking about how to avoid conflicts, and how to resolve conflicts that can't be avoided.
