### ISSUE TITLE
Number is sent as Double to server

### ISSUE THREAD

**Issue by graphicsxp** [Breeze/breeze-client#40]
When building a query with a literal predicate, if the value is a number, breeze sends the dataType as double. This happens here, line 238.

![Capture d’écran 2021-03-24 154613](https://user-images.githubusercontent.com/4160415/112330198-1f2f5980-8cb8-11eb-964f-976389291db6.jpg)

![image](https://user-images.githubusercontent.com/4160415/112330382-471ebd00-8cb8-11eb-85aa-6a49908d7d01.png)

Ending up with this error from server side (breeze .net  core 3)

![image](https://user-images.githubusercontent.com/4160415/112331335-1c813400-8cb9-11eb-9f96-f1e9266f32aa.png)

This is how my predicate is created :  
`return Predicate.and(new Predicate("RemainingPercentage", "eq", { value: this.value , isLiteral: true } ));`

I could change this code to 

` return Predicate.and(new Predicate("RemainingPercentage", "eq", { value: this.value , dataType: breeze.DataType.Decimal} ));`

but I don't want to hardcode it as it needs to remain generic. 

Could numbers be sent as decimal ? Or do I need to explicitly set the data type ?

**Comment by steveschmitt** [comment]
I can't reproduce this.  When I use:
```js
new Predicate("freight", "eq", { value: freightValue , isLiteral: true })
```
Breeze sends the query to the server with:
```
{"where":{"Freight":{"value":500,"dataType":"Decimal"}}}
```
I think Breeze gets the `dataType` from the metadata for the entity property.  What does your metadata have for `RemainingPercentage`?

**Comment by steveschmitt** [comment]
@graphicsxp Any more clues about this one?

**Comment by graphicsxp** [comment]
@steveschmitt  the metadata are : 

![image](https://user-images.githubusercontent.com/4160415/115508358-7e639800-a27d-11eb-8089-a4c185563ef6.png)


As you can see, it is a decimal so I would excpect breeze to query using the Decimal type. I don't why you cannot reproduce this issue. 

![image](https://user-images.githubusercontent.com/4160415/115509082-5163b500-a27e-11eb-972e-0de30d9a36ac.png)

I'm using breeze-client 2.0.11. 

When I call executeQuery, the json query is built and when it reaches the below code, the value (23 in this case) is considered as a Double (I don't even see Decimal in the switch statement)  

![image](https://user-images.githubusercontent.com/4160415/115512191-fd5acf80-a281-11eb-877f-3f09c4eb48f9.png)

I don't know how it is possible that we have a different behavior for this use-case :(

**Comment by steveschmitt** [comment]
In my case, `fromValue()` is not called, because the DataType is known already.  

During the creation of the **where** clause, the Predicate is converted to JSON, and this `_validate` function is called:

![image](https://user-images.githubusercontent.com/1671862/115604661-795f1280-a296-11eb-9b18-2378e3abbdfa.png)

In the code above, the `createExpr` function creates the predicate expression using the DataType for the property, which it gets from the EntityType.

I don't know why you are not getting the DataType from the `_validate` function.

**Comment by steveschmitt** [comment]
Perhaps the problem is the same as in #47 : Breeze does not know the EntityType for the query endpoint, so it can't determine the DataType.  

I tried it again, using the same predicate:
```js
var freightValue = 388.98;
var pred = Predicate.create("freight", "eq", { value: freightValue , isLiteral: true })
```
If I use the standard endpoint for the Order entity, then it works fine:
```js
var query = EntityQuery.from("Orders").where(pred); // query has "dataType": "Decimal"
```
But if I change the endpoint to "OrdersAgain", which is not in the metadata, then Breeze has to guess the datatype:
```js
var query = EntityQuery.from("OrdersAgain").where(pred); // query has "dataType": "Double"
```
The fix is to use `toType` so that Breeze knows the EntityType and can determine the DataType of the property:
```js
var query = EntityQuery.from("OrdersAgain").toType("Order").where(pred); // query has "dataType": "Decimal"
```
Hope this helps.
